# Generated by Django 4.2.4 on 2023-09-22 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('gov_id', models.IntegerField()),
                ('check_in', models.DateTimeField(auto_now=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests_by_room_category', to='hotelapp.room')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests_by_room_no', to='hotelapp.room')),
            ],
        ),
    ]
