# Generated by Django 4.2.4 on 2023-09-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_remove_guest_room_category_alter_guest_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='check_in',
        ),
        migrations.AddField(
            model_name='guest',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
